### ISSUE TITLE
Nekompatibilní s WW2 modpackem

### ISSUE THREAD

**Issue by WendaFCZE** [tenondra/OpenMissionFramework#2]
Když ten framework zkopíruju do své mise, tak to vyhodí error, že chybí módy: FIR-PilotCrewPack a BCTracers_Edited_hlc. Any solutions?

**Comment by WendaFCZE** [comment]
![arma3_x64 2017-08-18 16-10-58-45](https://user-images.githubusercontent.com/31134791/29462508-e9898aba-842f-11e7-895b-4bd4d83e8479.png)

**Comment by vy3si** [comment]
fast solution: delete these addons (displayed in red) from addon list in mission.sqm file (addons[]={....)

**Comment by tenondra** [comment]
´FIR nemám tušení proč tam je, ale už tam není. No a BCT je tvůj error. Mise nebyla tvořená s BC takže sis ji s tím musel zaponout sám.
