### ISSUE TITLE
Bug report ze Středeční mise

### ISSUE THREAD

**Issue by WendaFCZE** [tenondra/OpenMissionFramework#3]
Nějaké nedostatky ve frameworku ze středeční mise:
1) Když se člověk přiblíží k objektu (někdy pod 20 někdy pod 5 metrů) začne Zeus krvácet. Stalo se nám to tolikrát, až Zeus umřel.
2) Já jako additional Zeus jsem si nemohl přidávat objekty do Zeuse
3) AI dělali všechno až na potřetí, počtvrtý, pokud to vůbec pochopili.
4) V Zeusovi strašně fičí a po třiceti minutách už toho člověk má fakt dost.

**Comment by tenondra** [comment]
1. Chyba TFAR
2. Weird, podívám se na to
3. VComAI
4. viz 1
