### ISSUE TITLE
Zeus 1 

### ISSUE THREAD

**Issue by Damnik** [tenondra/OpenMissionFramework#4]
Zkoušel jsem nový Framework. Zeus prý má fungovat bez admina a tak jsem to zkoušel. Nalezl jsem problém, že sice ZEUS 3 je přístupný bez admina, ale ze Zeuse 1 se tam nedostanu.

**Comment by Damnik** [comment]
+ tak všechny problémy co jsme hlásili před tím tak platí z vyjímkou Zeuse 3

**Comment by tenondra** [comment]
Tzn. 1 a 2 fungovali vklidu?

**Comment by Damnik** [comment]
Právě naopak. Zeus 3 úplně v pohodě a bez problémů. Vše pracovalo jak by mělo. Ale Zeus 1 a 2 měli stále ty potíže co byli u první verze 3.4 - viz. Vítr, zraňování zeuse či nemožnost se dostat do zeuse bez admina

**Comment by tenondra** [comment]
Teď jsem to testoval na serveru - Zeus 1 funguje vpohodě. Akorát nemsíš být přihlášenej na adminovi a pak se odhlásit - to toho Zeuse logicky mít nebudeš. Stačí se pak znovu slotnout na toho Zeuse. Ještě nesmíš zapomenout zmáčknout "Z" ;)
